import {writeFileSync,mkdirSync} from 'node:fs';
const projects=[
{id:'knowledge',name:'AI 경기 리뷰 지식베이스',category:'루모스 / 검색과 답변 평가',period:'2026.06 – 2026.09',role:'데이터 수집과 검색 구조 설계부터 평가 체계 구축까지 주도',stack:'Python / 구조화 검색 / LLM 질의 라우팅 / 회귀 평가',metric:'51 → 80',unit:'90회 평가 중 자동 통과 응답',desc:'문서를 찾았는데도 답변이 틀리는 이유를 추적했습니다.',summary:'검색에 성공한 것과 질문에 제대로 답한 것은 달랐습니다. 의도 분류부터 근거 전달과 채점까지 나눠 살피며 AI 경기 리뷰용 지식베이스를 개선했습니다.',sections:[
['problem','어려웠던 점',`<p>게임 규칙과 통계는 갱신 주기가 다릅니다. 같은 챔피언에 관한 자료라도 패치 기준이 다르면 조언이 어긋날 수 있어 출처와 버전을 구분한 지식베이스가 필요했습니다.</p><p>자료를 모으고 검색 기능을 구현한 뒤에도 문제가 남았습니다. 검색 회귀 테스트는 통과했지만 실제 질문에서는 필요한 조건을 빠뜨리거나 자료가 있는데도 답할 수 없다는 응답이 나왔습니다. 어느 단계에서 정보가 누락되는지 밝히는 일이 가장 어려웠습니다.</p>`],
['structure','구현한 구조',`<p>원천 자료에서 바로 답변을 만들기보다 검증한 문서와 구조화된 색인을 미리 준비했습니다. 질문을 해석하는 단계와 문서를 검색하는 단계를 분리해 같은 입력의 검색 결과를 다시 확인할 수 있도록 했습니다.</p>${flow([['출처별 수집','규칙과 통계의 버전 기록'],['문서 검증','검증한 위키와 색인 준비'],['질의와 검색','의도 분류 후 근거 발췌'],['답변과 평가','질문과 원문을 함께 대조']])}<p class="note">구현 흐름을 설명하기 위해 재구성한 개념도입니다. 이 프로젝트의 검색은 임베딩 유사도 대신 구조화된 색인과 규칙을 사용합니다.</p><p>LLM이 질문의 의도를 구조화하면 검색기가 해당 문서와 필요한 구절을 찾아 전달합니다. 검색기 자체는 LLM이나 외부 네트워크를 호출하지 않도록 구성했고 의도 분류가 실패하는 경우에는 키워드 기반 경로를 두었습니다.</p>`],
['decisions','판단과 수정',`<h3>자료를 더 넣기 전에 전달 경로부터 확인했습니다</h3><p>의도 분류 결과와 검색된 발췌문 그리고 최종 답변을 기록해 비교했습니다. 챔피언 약칭을 인식하지 못한 경우와 문서를 찾고도 필요한 조건을 전달하지 못한 경우를 구분했습니다.</p><table class="comparison"><thead><tr><th>실패 사례</th><th>수정한 지점</th></tr></thead><tbody><tr><td>‘킨드’를 챔피언으로 인식하지 못함</td><td>약칭을 별칭 색인에 연결</td></tr><tr><td>스킬 발동 순서를 빌드 순서로 해석</td><td>질문 의도 분기 수정</td></tr><tr><td>일반 칼바람 질문을 증강 질문으로 처리</td><td>스킬과 증강의 검색 경로 분리</td></tr></tbody></table><p>이 사례들은 이미 보유한 사실을 찾아 전달하는 과정의 문제였습니다. 해당 개선 단계에서는 위키 사실 본문을 다시 쓰지 않고 검색과 전달 경로를 수정했습니다.</p><h3>자동 채점 결과도 원문과 대조했습니다</h3><p>브라움 패시브에 대한 답변은 첫 중첩과 아군 공격에 의한 기절 조건을 설명했는데도 실패로 판정됐습니다. 질문하지 않은 추가 피해 설명이 없다는 것이 이유였습니다. 답변 오류와 채점 오류를 구분하고 질문에서 요구한 조건을 충족했는지 별도로 검토했습니다.</p><p>자동 실패 기록을 지우거나 통과할 때까지 답변을 다시 생성하지 않았습니다. 원래의 판정과 검토 결과를 각각 남겨 점수가 달라진 이유를 추적할 수 있도록 했습니다.</p>`],
['results','결과와 해석',`<div class="result"><strong>51/90 → 80/90</strong><p>동일한 30개 질문을 개선 전후 각각 3회씩 실행했을 때의 자동 통과 응답 수입니다.</p></div><p>저장된 2026년 9월 8일 평가 보고서를 기준으로 정리했습니다. 검색 회귀 테스트 1,833개도 통과했지만 검색 회귀와 실제 답변 평가는 서로 다른 검사이므로 결과를 나눠 기록했습니다.</p><p class="note">근거 기록: reports/live-quality-213/final.md. 이 수치는 정해진 질문 표본과 보유 자료에 대한 결과이며 전체 서비스 정확도나 실제 사용자 만족도를 뜻하지 않습니다. 리뷰 기능용 지식베이스 구축 및 평가 사례로 소개합니다.</p>`],
['learning','달라진 개발 방식',`<p>AI가 오답을 내면 프롬프트부터 바꾸기보다 원천 자료와 검색 경로 그리고 평가 기준을 나눠 확인합니다. 통과율이 올랐다는 사실만으로 개선을 판단하지 않고 어떤 실패를 해결했는지 설명할 수 있는 기록을 남깁니다.</p><p>기업 문서를 다루는 AI에서도 답변과 근거가 연결되는지 확인하는 일이 필요합니다. 이 프로젝트에서 쌓은 검색 경로 분석과 평가 경험을 그 과정에 활용하고 싶습니다.</p>`]
]},
{id:'documents',name:'사내 기술문서 검색 데이터 자동화',category:'한국타이어앤테크놀로지 / R&D DX 인턴',period:'2025.09 – 2025.12',role:'문서 정제 담당. 변환 도구 비교와 청킹 기준 수립 및 색인 자동화 수행',stack:'Python / MarkItDown / 한컴 변환 도구 / OpenSearch',metric:'2,000',unit:'검색 데이터로 가공한 기술문서 약 2,000건',desc:'표의 의미를 보존하며 문서 처리와 색인을 자동화했습니다.',summary:'문서가 변환됐다는 것만으로 검색에 쓸 수 있는 것은 아니었습니다. 연구원이 답변 근거를 확인할 수 있도록 표와 제목 구조를 보존하는 데 집중했습니다.',sections:[
['problem','업무의 출발점',`<p>사내 기술문서 약 2,000건을 AI 챗봇의 검색 데이터로 가공하는 업무를 맡았습니다. PDF와 PPT부터 HWP까지 문서 형식이 다양해 수작업 변환과 정제에 약 두 달이 예상됐습니다.</p><p>처리 시간뿐 아니라 변환 품질도 문제였습니다. 표가 깨지면 항목과 수치의 관계가 사라져 문장을 검색하더라도 연구원이 잘못된 정보를 얻을 수 있었습니다.</p>`],
['structure','자동화한 범위',`${flow([['문서 변환','형식별 변환 도구 선택'],['정제','반복 영역 제거와 구조 보존'],['청킹과 임베딩','제목과 본문 기준으로 분할'],['검색 색인','OpenSearch에 적재']])}<p>처음 맡은 문서 정제에서 작업 범위를 넓혀 임베딩 생성과 검색 색인까지 Python으로 연결했습니다. 반복 실행이 필요한 작업을 하나의 흐름으로 묶고 연구원의 피드백을 정제 기준에 반영했습니다.</p><p class="note">업무 구조를 설명하기 위한 개념도입니다. 사내 원문과 실제 연구 데이터는 포함하지 않았습니다.</p>`],
['decisions','기술적 판단',`<h3>처리 속도보다 문서 구조를 먼저 비교했습니다</h3><p>같은 문서를 MarkItDown과 한컴 변환 도구로 각각 처리해 표와 제목 구조가 얼마나 유지되는지 살폈습니다. 한 도구로 모든 형식을 처리하지 않고 문서 형식별로 적합한 도구를 선정했습니다.</p><p>Markdown 변환 결과에서는 반복되는 머리말과 꼬리말을 제거하고 제목 계층을 보존하도록 정제 기준을 코드에 반영했습니다.</p><h3>사용자 의견을 문서 분할 기준으로 바꿨습니다</h3><p>연구원에게서 답변이 문서의 어느 대목을 근거로 삼았는지 알기 어렵다는 의견을 받았습니다. 제목과 본문 구조를 기준으로 청킹 경계를 정하고 변환 결과를 함께 확인하며 보정했습니다. 단순히 일정한 길이로 자르는 것보다 내용의 맥락을 유지하는 것이 우선이었습니다.</p>`],
['results','처리 결과',`<div class="result"><strong>2개월 예상 → 1개월 이내</strong><p>약 2,000건의 문서 처리를 예상 기간보다 앞당겨 마쳤습니다.</p></div><p>연구원들에게서 실무에 쓸 만하고 오류도 거의 없다는 평가를 받았습니다. 이 평가는 실제 사용자에게 받은 정성적 피드백이며 별도로 측정한 검색 정확도 수치는 아닙니다.</p>`],
['learning','업무에 남은 기준',`<p>데이터 전처리의 완료 기준을 파일 생성 여부에 두지 않게 됐습니다. 사용자가 답변을 이해하고 근거를 확인할 수 있는지 살피며 도구와 정제 기준을 선택합니다. AI 기능을 업무에 적용하려면 사용자 의견이 코드의 어떤 기준으로 이어지는지까지 구체화해야 한다는 것을 배웠습니다.</p>`]
]},
{id:'desktop',name:'실시간 AI 코칭 데스크톱 앱',category:'루모스 / LOLPAGO 서비스 개발과 운영',period:'2026.02 – 현재',role:'팀 프로젝트의 기획과 개발을 주도. 클라이언트 개발부터 빌드와 배포 및 운영 문제 대응',stack:'React / Electron / TypeScript / MySQL / REST API / WebSocket',metric:'24%',unit:'틱당 전송량 감소',desc:'게임과 함께 실행되는 환경에서 성능과 안내 오류를 개선했습니다.',summary:'화면을 구현하는 것에서 시작해 게임과 동시에 실행될 때의 성능과 음성 안내까지 살폈습니다. 사용자가 받는 결과를 기준으로 수정 범위를 정했습니다.',sections:[
['problem','만들고 운영한 서비스',`<p>LOLPAGO는 경기 데이터와 실시간 정보를 바탕으로 코칭을 전달하는 데스크톱 앱입니다. 팀과 함께 개발하며 서비스 기획부터 클라이언트 구현과 배포까지 주도했습니다.</p><p>게임 도중에는 화면을 오래 읽기 어렵습니다. 화면 안내와 TTS 음성을 함께 제공했고 공식 API만으로 확인하기 어려운 정보는 화면 캡처와 비전 인식 및 OCR로 보완했습니다.</p><figure class="compact-shot"><img src="../assets/coaching.png" width="429" height="207" alt="게임 화면 위에 표시되는 LOLPAGO 플레이 코치 메시지" loading="lazy"><figcaption>실제 코칭 오버레이 화면. 아래 성능 수치의 측정 자료가 아닌 UI 예시입니다.</figcaption></figure>`],
['structure','개발 범위',`${flow([['경기 데이터','Riot API 수집과 가공'],['저장과 제공','MySQL과 자체 API'],['클라이언트','React와 Electron'],['실시간 전달','화면 메시지와 TTS']])}<p>수집한 경기 데이터를 MySQL에 저장하고 서비스에서 쓰기 쉬운 형태로 가공해 자체 API로 제공했습니다. React와 Electron으로 클라이언트를 구현한 뒤 빌드와 코드 서명 및 버전 배포까지 진행했습니다.</p><p class="note">기능별 역할을 요약한 개념도입니다. 실시간 캡처와 코칭 경로 전체를 직렬 처리한다는 의미는 아닙니다.</p>`],
['decisions','운영 중 해결한 문제',`<h3>게임과 함께 실행되는 환경에서 성능을 확인했습니다</h3><p>앱 단독 실행에서는 드러나지 않던 프레임 저하가 게임과 동시에 실행할 때 나타났습니다. Base64 기반 전송을 바이너리 방식으로 바꾸고 이미지와 이벤트 처리 구조를 개선했습니다.</p><div class="result"><strong>약 100 → 150–200 FPS</strong><p>개선 과정에서 확인한 게임 프레임 변화입니다. 틱당 전송량은 24% 줄었습니다.</p></div><p class="note">개발 과정에서 관찰한 환경 기준의 수치입니다. 전송 방식과 처리 구조를 함께 개선한 결과이며 모든 PC의 성능을 보장하거나 전송량 감소만의 효과를 분리 측정한 결과는 아닙니다.</p><h3>잘못된 안내를 화면과 음성에서 함께 막았습니다</h3><p>드래곤이 등장하지 않는 칼바람 모드에서 드래곤 코칭이 나가는 문제가 있었습니다. 게임 모드와 대전 유형을 함께 확인해 차단하고 메시지 식별자로 연결된 TTS 오디오 청크도 재생하지 않도록 수정했습니다.</p><p>차단 여부를 살피다 메인 창이 자신이 요청하지 않은 코칭 오디오까지 재생하는 별개의 오류를 발견했습니다. 재생 로직까지 수정해 화면에서 메시지가 사라진 뒤에도 음성 안내가 남을 수 있는 경로를 막았습니다.</p>`],
['results','배포 이후까지 맡은 일',`<p>사용자의 실행 환경에서 발생하는 문제를 받아 원인을 좁히고 수정 버전을 배포했습니다. 클라이언트 인식 문제는 설치 경로에 의존하지 않는 방식으로 바꿨으며 변경 내용을 공지로 알렸습니다.</p><p>기능 구현과 배포를 별개의 일로 보지 않게 됐습니다. 수정한 코드뿐 아니라 화면과 음성 같은 다른 전달 경로에도 영향이 남는지 확인합니다.</p><a class="external" href="https://lolpago.com/" target="_blank" rel="noopener noreferrer">LOLPAGO 서비스 사이트 ↗</a>`],
['learning','AX 업무에 가져갈 경험',`<p>AI 기능도 기존 서비스의 데이터와 실행 환경 안에서 동작해야 합니다. API 연결과 클라이언트 개발을 함께 맡았던 경험을 바탕으로 다른 팀과 데이터 형식과 호출 시점을 구체적으로 조율하고 배포 이후의 문제까지 살피겠습니다.</p>`]
]},
{id:'superchacha',name:'학내 챗봇 통합 플랫폼',category:'슈퍼차차 / 3인 팀 프로젝트',period:'2025.05 – 2025.09',role:'기획과 구조 설계 및 프론트엔드 개발. 임베딩 기반 챗봇 자동 연결 구현',stack:'React / FastAPI / 임베딩 / FAISS',metric:'3 → 1',unit:'챗봇을 찾는 탐색 단계',desc:'사용자가 담당 부서를 몰라도 질문부터 시작하도록 바꿨습니다.',summary:'학내 챗봇이 여러 곳에 나뉘어 있으면 사용자가 먼저 담당 부서를 알아야 했습니다. 질문의 의미에 맞는 챗봇을 연결하는 통합 플랫폼을 만들었습니다.',sections:[
['problem','사용자에게 남아 있던 일',`<p>필요한 답을 얻으려면 사용자가 질문할 분야를 분류하고 담당 챗봇을 찾아야 했습니다. 챗봇이 있어도 어디에 물어봐야 하는지 모르면 탐색 부담이 남았습니다.</p><p>3인 팀에서 기획과 구조 설계를 맡고 프론트엔드와 자동 연결 기능을 개발했습니다. 사용자가 서비스 분류 체계를 먼저 익히지 않아도 질문을 시작할 수 있도록 만드는 것이 목표였습니다.</p><figure><img src="../assets/superchacha.png" width="1901" height="869" alt="질문을 입력하면 적합한 챗봇을 연결하는 슈퍼차차 홈 화면" loading="lazy"><figcaption>직접 개발한 슈퍼차차 홈 화면</figcaption></figure>`],
['structure','질문에서 챗봇으로',`${flow([['질문 입력','부서를 고르지 않고 질문'],['임베딩','질문의 의미를 벡터화'],['챗봇 매칭','적합한 챗봇 검색'],['연결','해당 챗봇에서 질문 처리']])}<p>질문의 의미를 임베딩으로 표현해 알맞은 챗봇을 찾도록 구현했습니다. 사용자는 챗봇 목록을 직접 훑는 대신 질문을 먼저 입력할 수 있습니다.</p>`],
['decisions','연결 품질과 사용 흐름',`<p>연결 기능은 동작 여부만으로 판단하기 어려웠습니다. 표현이 달라도 같은 분야를 찾는지 확인하면서 분류 결과를 살폈고 사용자가 질문을 입력하는 화면과 연결 흐름을 함께 수정했습니다.</p><p>학내 질문이라는 범위 안에서 챗봇을 선택하도록 구성했습니다. 질문을 분류하는 정확도와 연결된 챗봇의 답변 품질은 다른 문제이므로 탐색 과정의 개선을 전체 답변 정확도로 표현하지 않았습니다.</p>`],
['results','변화와 성과',`<div class="result"><strong>3단계 → 1단계</strong><p>질문에 맞는 챗봇을 자동으로 연결해 탐색 과정을 줄였습니다.</p></div><p>생성형 AI 활용 경진대회에서 은상을 받았습니다. 사용자가 필요한 정보에 도달하는 과정을 직접 바꿔보며 AI를 서비스에 연결하는 개발에 관심을 갖게 됐습니다.</p><a class="external" href="https://github.com/bgp-llama/llm-contest-fe" target="_blank" rel="noopener noreferrer">프론트엔드 GitHub ↗</a><a class="external" href="https://bgp-llama.github.io/llm-contest-fe/" target="_blank" rel="noopener noreferrer">공개 화면 ↗</a><p class="note">공개 화면의 질문 실행은 별도 백엔드 운영 상태에 따라 제한될 수 있습니다.</p>`],
['learning','이후의 관심',`<p>어떤 모델을 사용할지 정하는 일만큼 사용자가 그 결과를 어디서 어떻게 받는지 설계하는 일이 중요했습니다. 이후 문서 처리와 데스크톱 앱 개발에서도 데이터와 사용자 흐름을 함께 살피는 방식으로 작업했습니다.</p>`]
]}
];
function flow(items){return `<div class="flow" role="list">${items.map(([a,b])=>`<div role="listitem">${a}<small>${b}</small></div>`).join('')}</div>`}
function shell(title,body,depth='',active='projects'){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | 양준혁</title><meta name="description" content="양준혁의 AI 개발 포트폴리오. 문서 데이터 처리와 AI 답변 검증부터 데스크톱 앱 배포와 운영까지 수행한 경험을 소개합니다."><meta name="theme-color" content="#243d36"><meta property="og:title" content="${title} | 양준혁"><meta property="og:description" content="데이터 처리에서 답변 검증과 서비스 운영까지. 다우기술 AI 개발 지원 포트폴리오."><meta property="og:type" content="website"><link rel="icon" href="${depth}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${depth}styles.css"></head><body><a class="skip" href="#main">본문으로 건너뛰기</a><aside class="rail"><div class="identity"><a class="monogram" href="${depth}index.html" aria-label="양준혁 포트폴리오 홈">Y.</a><div class="person">양준혁</div><div class="role">AI Developer</div><img class="portrait" src="${depth}assets/portrait.jpg" alt="양준혁 증명사진" width="104" height="139"></div><nav aria-label="주요 메뉴"><a href="${depth}index.html#projects" ${active==='projects'?'aria-current="page"':''}>프로젝트 <small>04</small></a><a href="${depth}index.html#experience">경력</a><a href="${depth}index.html#skills">기술과 경험</a><a href="${depth}index.html#contact">연락처</a></nav><div class="rail-bottom">다우기술 AI 개발 지원<br>면접 참고 포트폴리오<a href="https://github.com/banbakbulga" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></aside><main id="main"><div class="topline"><span>JUNHYUK YANG / PORTFOLIO</span><span>2026.09</span></div>${body}<footer class="foot"><span>양준혁 / AI 개발 포트폴리오</span><button class="text-button" type="button" data-print>이 페이지 인쇄 / PDF 저장</button></footer></main><script src="${depth}main.js"></script></body></html>`}
const home=`<header class="intro"><h1>데이터를 다듬고 답변을 검증하며<br>실제로 쓰이는 AI를 만듭니다.</h1><p>안녕하세요. 개발자 양준혁입니다.<br>사내 문서의 검색 데이터 가공부터 AI 코칭 앱의 개발과 배포까지 맡았습니다. 기능이 동작한 뒤에도 사용 과정에서 생기는 문제를 찾아 개선합니다.</p></header><section id="projects"><div class="index-head"><h2>주요 프로젝트</h2><span>문제와 판단을 중심으로 정리했습니다</span></div>${projects.map(p=>`<a class="project-row" href="projects/${p.id}.html"><div><div class="project-meta">${p.category}</div><h3>${p.name}</h3><p>${p.desc}</p></div><div class="metric"><strong>${p.metric}</strong><span>${p.unit}</span></div><span class="row-arrow" aria-hidden="true">↗</span></a>`).join('')}</section><section class="section" id="experience"><h2>경력</h2><article class="experience"><time>2026.02.19 – 현재</time><div><h3>루모스 <span class="role">소프트웨어 개발부 / 정규직</span></h3><p>AI 코칭 서비스의 기획과 개발을 주도했습니다. React와 Electron 클라이언트 개발부터 데이터 API 연결과 버전 배포까지 맡고 실제 실행 환경에서 생기는 문제에 대응했습니다.</p></div></article><article class="experience"><time>2025.09 – 2025.12</time><div><h3>한국타이어앤테크놀로지 <span class="role">R&D DX / 인턴</span></h3><p>기술문서를 AI 챗봇의 검색 데이터로 가공했습니다. 연구원 피드백을 받아 문서 구조를 보존하는 정제 기준을 수립하고 임베딩 생성과 검색 색인을 자동화했습니다.</p></div></article></section><section class="section" id="skills"><h2>기술을 사용한 자리</h2><div class="skills-list"><div class="skill"><h3>AI 데이터와 검색</h3><p>Python으로 문서를 정제하고 OpenSearch 색인까지 연결했습니다. 임베딩 기반 챗봇 매칭과 구조화된 위키 검색을 서로 다른 문제에 적용했습니다. <a href="projects/documents.html">문서 처리 사례 ↗</a></p></div><div class="skill"><h3>답변 품질 검증</h3><p>질문 의도와 검색 근거 및 답변을 나눠 기록했습니다. 자동 판정과 원문 대조 결과를 구분해 검색 오류와 평가 오류를 각각 수정했습니다. <a href="projects/knowledge.html">평가 사례 ↗</a></p></div><div class="skill"><h3>서비스 개발과 운영</h3><p>React와 Electron으로 앱을 개발하고 MySQL 기반 데이터와 API를 연결했습니다. 실시간 통신의 전송량을 줄이고 코드 서명과 배포까지 진행했습니다. <a href="projects/desktop.html">운영 사례 ↗</a></p></div></div></section><section class="section" id="contact"><h2>함께 이야기하고 싶습니다</h2><div class="contact"><div class="contact-links"><a href="mailto:junh9126@gmail.com">junh9126@gmail.com ↗</a><a href="tel:+821057661639">+82 10-5766-1639</a><a href="https://github.com/banbakbulga" target="_blank" rel="noopener noreferrer">github.com/banbakbulga ↗</a></div><p>프로젝트의 구현 과정과<br>판단 근거를 더 자세히 설명드리겠습니다.</p></div></section>`;
mkdirSync('projects',{recursive:true});writeFileSync('index.html',shell('AI 개발 포트폴리오',home));
projects.forEach((p,i)=>{const next=projects[(i+1)%projects.length];const body=`<header class="case-header"><div class="project-meta">${p.category}</div><h1>${p.name}</h1><p class="summary">${p.summary}</p></header><dl class="case-meta"><div><dt>기간</dt><dd>${p.period}</dd></div><div><dt>내가 맡은 일</dt><dd>${p.role}</dd></div><div style="grid-column:1/-1"><dt>사용 기술</dt><dd>${p.stack}</dd></div></dl><div class="case-layout"><article class="case-body">${p.sections.map(([id,title,content])=>`<section id="${id}"><h2>${title}</h2>${content}</section>`).join('')}</article><nav class="toc" aria-label="이 프로젝트 목차"><span>이 프로젝트에서</span>${p.sections.map(([id,t])=>`<a href="#${id}">${t}</a>`).join('')}</nav></div><div class="case-next"><a href="../index.html#projects">← 프로젝트 목록</a><a href="${next.id}.html">다음 프로젝트 →</a></div>`;writeFileSync(`projects/${p.id}.html`,shell(p.name,body,'../'));});
